### ISSUE TITLE
LFS bandwidth problem

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/emtsv#12]
I got the following error message when installing emtsv:
```
Error downloading object: purepos/szeged.model (07babe0): Smudge error: Error downloading purepos/szeged.model (07babe0a53f0caec60c0a1005bddbc21c3275c88eab27922e22a343e5f316a38): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by dlazesz** [comment]
Thank you for reporting this issue and sorry for the delayed reply.

The hashes in the error message is originated from an old commit, which refers to an LFS file in a submodule from [ppke-nlpg](https://github.com/ppke-nlpg/purepospy/blob/master/purepos/szeged.model) that had been moved in a later commit.

The solution is the following:

Do not clone the full repo only do shallow clone as it is stated in [the updated documentation](https://github.com/dlt-rilmta/emtsv/blob/ba8dee3fcd07808fe924e8d2553bb6ff4b4187d2/doc/installation.md#clone-the-repository) 

We are moving away from git submodules and LFS files to use python packages instead. This would solve all LFS related problems. We made good progress, but we need some more time to smooth out the rough edges (e.g. the unified handling of the very large models of emBERT). If you do not wan to use emBERT you can ommit downloading LFS files as all the other modules had moved already.

I close this issue as the documentation has been upgraded to avoid this issue and hopefully soon we can address the root of the problem too.
