### ISSUE TITLE
hfstana/xpostag OTHER value

### ISSUE THREAD

**Issue by softwaretailoring** [dlt-rilmta/emtsv#18]
First of all, congratulations on the new architecture of emtsv. It's much better than the previous one (e-magyar.hu/GATE).
Köszönöm! :)

I have a project which used the e-magyar.hu tsv format until these days.
There was an OTHER value in the hfstana column.
The emtsv result contains a morph code instead of it in the xpostag column.
I investigated it with [Punct] mainly.

Does the OTHER value still exist?

**Comment by dlazesz** [comment]
As the OTHER value encoded punctuation in most of the cases it has been renamed to [Punct] to be more meaningful.
OTHER values should not exist anymore.

Have you find some evidence on the contrary?

**Comment by softwaretailoring** [comment]
No, I didn't find such value.
I would have liked knowing that it does exist or not.
Thanks!
