### ISSUE TITLE
analysing old Hungarian texts

### ISSUE THREAD

**Issue by sassbalint** [dlt-rilmta/emtsv#20]
How can we make `emtsv` to be able to analyse old Hungarian texts?

I guess we should...

 * replace `hu.hfstol` to another HFST file which deals with old Hungarian morphology [in `emmorphpy`.](https://github.com/dlt-rilmta/emmorphpy/tree/master/emmorphpy)
 * create a new module here in `emtsv`.

Am I right?

**Comment by dlazesz** [comment]
emMorphPy needs two parameters to work:
- The mentioned hu.hfstol
- [The props](https://github.com/dlt-rilmta/emmorphpy/blob/master/emmorphpy/hfst-wrapper.props) file for emLem configuration

Both can be replaced at init time as [parameters](https://github.com/dlt-rilmta/emmorphpy/blob/master/emmorphpy/emmorphpy.py#L21) in [config.py](https://github.com/dlt-rilmta/emtsv/blob/master/config.py#L20).

However, to get POS tagging work the PurePOS model also have to be replaced.

**Comment by sassbalint** [comment]
Thanks, @dlazesz Balázs! Can be closed.
