### ISSUE TITLE
feature request: maxlen switch a depelemzőbe

### ISSUE THREAD

**Issue by sassbalint** [dlt-rilmta/emtsv#9]
@dlazesz Balázs, esetleg bele tudnád ez tenni a depelemző modulba? :)

```
switch: --maxlen <NUMBER>

if --maxlen:
  process = real_process_with_maxlen
else:
  process = real_process

def real_process:
  ...


def real_process_with_maxlen:
  if sent.length > --maxlen:
    real_process()
  else:
    hoeses()

process( sent )
```

Így akkor csak akkor lassít a mondatonként +1 if, ha van `--maxlen` kapcsoló.

**Comment by dlazesz** [comment]
Done in d21ba64. See https://github.com/dlt-rilmta/emdeppy#usage for CLI usage. In emtsv one must set the number as kwarg in config.py.
